docker-deploy/amazon/amazon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('web.urls')),
    path('admin/', admin.site.urls),
]

docker-deploy/amazon/web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.login, name='login'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('index/', views.index, name='index'),
    path('public/', views.public, name='public'),
    path('checkout/', views.checkout, name='checkout'),
    path('cart/', views.cart, name='cart'),
    path('delete-cart/<slug:slug>', views.delete_cart, name='delete_cart'),
    path('production/<slug:slug>', views.production, name='production'),
    path('myorder/', views.myorder, name='myorder'),
    path('order-detail/<slug:slug>', views.order_detail, name='order_detail'),
    path('rebind-ups/<slug:slug>', views.rebind_ups, name='rebind_ups'),
]

docker-deploy/amazon/templates/web/cart.html
<html>

<head>
  <meta charset="UTF-8">
  <title>Home Page</title>
</head>

<body>
  <div id="includedContent"></div>
  <div class="container-xl px-4 mt-4">
    <div>
      {% if error_message %}
      <a href="#">
        <button type="button" class="btn btn-primary disabled" name='Checkout'>Checkout
        </button>
      </a>
      {% else %}
      <a href="{% url 'web:checkout'%}">
        <button type="button" class="btn btn-primary" name='Checkout'>Checkout
        </button>
      </a>
      {% endif %}
    </div>
    {% if error_message %}
    <div class="alert alert-primary" data-dismiss="alert">
      {{error_message}}
    </div>
    {% endif %}
    <table border="1" id="example" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr>
          <th>Name</th>
          <th>Amount To Buy</th>
          <th>Detail</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for production in cart_production_list %}
        <tr>
          <td>{{ productionNameMap|get_item:production.production_id }}</td>
          <td>{{ production.amount }}</td>

          <td><a href="{% url 'web:production' slug=production.production_id %}">
              <button type="button" class="btn btn-primary">View Detail</button>
            </a>
          </td>
          <td>
            <a href="{% url 'web:delete_cart' slug=production.id %}">
              <button type="button" class="btn btn-danger" name='delete this goods'>Delete
              </button>
            </a>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
</body>

</html>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script>
  $(function () {
    $("#includedContent").load("../public");
  });
  $(document).ready(function () {
    $('#example').DataTable();
  });
</script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">

docker-deploy/amazon/templates/web/checkout.html
<html>

<head>
  <meta charset="UTF-8">
  <title>Home Page</title>
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script>
    $(function () {
      $("#includedContent").load("../public");
    });
  </script>
</head>

<body>
  <div id="includedContent"></div>
  <div class="container-xl px-4 mt-4">
    <div class="row">
      <div class="col-xl-8">
        <!-- Account details card-->
        <div class="card mb-4">
          <div class="card-header">Checkout
          </div>
          <div class="card-body">
            <form action="{% url 'web:checkout' %}" method="post">
              {% csrf_token %}
              {% if error_message %}
              <div class="alert alert-primary" data-dismiss="alert">
                {{error_message}}
              </div>
              {% endif %}
              <div class="row gx-3 mb-3">
                <!-- Form Group (organization name)-->
                <div class="col-md-6">
                  {{ checkout_form.x.label }}
                  {{ checkout_form.x }}
                </div>
                <!-- Form Group (location)-->
                <div class="col-md-6">
                  {{ checkout_form.y.label }}
                  {{ checkout_form.y }}
                </div>
              </div>
              <div class="row gx-3 mb-3">
                {{ checkout_form.upsAcc.label }}
                {{ checkout_form.upsAcc }}
              </div>
              <div>
                <a href="{% url 'web:cart' %}" type="button" class="btn btn-primary" name='Back'>Back
                  to Cart
                </a>
                <button type="submit" class="btn btn-primary" name='add_to_cart'>Place the order
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

docker-deploy/amazon/templates/web/index.html
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Home Page</title>
</head>

<body>
  <div id="includedContent"></div>
  <div class="container-xl px-4 mt-4">
    <table border="1" id="example" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <!-- <th>Amount in stock</th> -->
          <th>Catalog</th>
          <th>Detail</th>
        </tr>
      </thead>
      <tbody>
        {% for production in production_list %}
        <tr>
          <td>{{ production.name }}</td>
          <td>{{ production.description }}</td>

          <!-- {% if production.name in production2amount %}
          <td>{{ production2amount|get_item:production.name }}</td>
          {% else %}
          <td>0</td>
          {% endif %} -->

          {% if production.catalog == 'F' %}
          <td>Food</td>
          {% else %}
          <td>Electronics</td>
          {% endif %}

          <td>
            <a href="{% url 'web:production' slug=production.id %}">
              <button type="button" class="btn btn-primary">View Detail</button>
            </a>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
</body>

</html>


<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script>
  $(function () {
    $("#includedContent").load("../public");
  });
  $(document).ready(function () {
    $('#example').DataTable();
  });
</script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">

docker-deploy/amazon/templates/web/login.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
</head>
<body>
<section class="vh-100">
    <div>
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                         class="img-fluid"
                         alt="Sample image">
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <form action="{% url 'web:login' %}" method="post">
                        {% csrf_token %}
                        {% if error_message %}
                        <div class="alert alert-primary" data-dismiss="alert">
                            {{error_message}}
                        </div>
                        {% endif %}
                        <div class="form-outline mb-4">
                            {{ login_form.name.label }}
                            {{ login_form.name }}
                        </div>
                        <div class="form-outline mb-3">
                            {{ login_form.password.label }}
                            {{ login_form.password }}
                        </div>
                        <div class="text-center text-lg-start mt-4 pt-2">
                            <button type="submit" class="btn btn-primary btn-lg"
                                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Login
                            </button>
                            <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a
                                    href="{% url 'web:register' %}"
                                    class="link-danger">Register</a></p>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>

docker-deploy/amazon/templates/web/myorder.html
<html>

<head>
  <meta charset="UTF-8">
  <title>Order Page</title>
</head>

<body>
  <div id="includedContent"></div>
  <div class="container-xl px-4 mt-4">
    <table border="1" id="example" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr>
          <th>Order Id</th>
          <th>Address</th>
          <th>Ups Account</th>
          <th>Tracking Number</th>
          <th>Status</th>
          <th>Detail</th>
          <th>Rebind</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
        <tr>
          <td>{{order.id}}</td>
          <td>({{order.destX}}, {{order.destY}})</td>
          {% if order.upsAcc != "" and order.upsAcc_valid %}
          <td>{{order.upsAcc}} (verified)</td>
          {% elif order.upsAcc != "" and not order.upsAcc_valid %}
          <td>{{order.upsAcc}} (unverified)</td>
          {% else %}
          <td style="color:rgb(180, 180, 180)">not binded</td>
          {% endif %}
          {% if order.tracking_number != "" %}
          <td>{{order.tracking_number}}</td>
          {% else %}
          <td style="color:rgb(180, 180, 180)">not generated</td>
          {% endif %}
          <td>
            {% if order.status == "B" %}
            Order Placed
            {% elif order.status == "P" %}
            Packing
            {% elif order.status == "L" %}
            Loading
            {% elif order.status == "T" %}
            On the way
            {% else %}
            Delivered
            {% endif %}
          </td>
          <td><a href="{% url 'web:order_detail' slug=order.id %}">
              <button type="button" class="btn btn-primary">View Detail</button>
            </a>
          </td>
          <td>
            {% if order.status != "D" %}
            <a href="{% url 'web:rebind_ups' slug=order.id %}">
              <button type="button" class="btn btn-primary">Rebind UpsAcc</button>
            </a>
            {% else %}
            <a href="#">
              <button type="button" class="btn btn-primary disabled">Rebind UpsAcc</button>
            </a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
</body>

</html>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script>
  $(function () {
    $("#includedContent").load("../public");
  });
  $(document).ready(function () {
    $('#example').DataTable();
  });
</script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">

docker-deploy/amazon/templates/web/order_detail.html
<html>

<head>
  <meta charset="UTF-8">
  <title>Order Detail Page</title>
</head>

<body>
  <div id="includedContent"></div>
  <div class="container-xl px-4 mt-4">
    <table border="1" id="example" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr>
          <th>Order Id</th>
          <th>Name</th>
          <th>Amount To Buy</th>
          <th>Detail</th>
        </tr>
      </thead>
      <tbody>
        {% for production in orderItems %}
        <tr>
          <td>{{ production.order_id }}</td>
          <td>{{ productionNameMap|get_item:production.production_id }}</td>
          <td>{{ production.amount }}</td>

          <td><a href="{% url 'web:production' slug=production.production_id %}">
              <button type="button" class="btn btn-primary">View Detail</button>
            </a>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
</body>

</html>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script>
  $(function () {
    $("#includedContent").load("../public");
  });
  $(document).ready(function () {
    $('#example').DataTable();
  });
</script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">

docker-deploy/amazon/templates/web/production.html
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Home Page</title>
</head>

<body>
  <div id="includedContent"></div>

  <div class="container-xl px-4 mt-4">
    <div class="row">
      <div class="col-xl-8">
        <!-- Account details card-->
        <div class="card mb-4">
          <div class="card-header">Production Detail (You may add as much production as you want to the cart)
          </div>
          <div class="card-body">
            <form action="{% url 'web:production' slug=production.id %}" method="post">
              {% csrf_token %}
              {% if error_message %}
              <div class="alert alert-primary" data-dismiss="alert">
                {{error_message}}
              </div>
              {% endif %}
              <div class="row gx-3 mb-3">
                <!-- Form Group (organization name)-->
                <div class="col-md-6">
                  {{ production_form.name.label }}
                  {{ production_form.name }}
                </div>
                <!-- Form Group (location)-->
                <div class="col-md-6">
                  {{ production_form.description.label }}
                  {{ production_form.description }}
                </div>
              </div>
              <div class="row gx-3 mb-3">
                <!-- Form Group (organization name)-->
                <!-- <div class="col-md-6">
                  {{ production_form.amount.label }}
                  {{ production_form.amount }}
                </div> -->
                <!-- Form Group (location)-->
                <div class="col-md-6">
                  {{ production_form.amount_to_buy.label }}
                  {{ production_form.amount_to_buy }}
                </div>
              </div>
              <div>
                <a href="{% url 'web:index' %}" type="button" class="btn btn-primary" name='Back'>Back
                  Home
                </a>
                <button type="submit" class="btn btn-primary" name='add_to_cart'>Add to Cart
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script>
  $(function () {
    $("#includedContent").load("../public");
  });
  $(document).ready(function () {
    $('#example').DataTable();
  });
</script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">

docker-deploy/amazon/templates/web/public.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">


<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    <a class="navbar-brand me-2" href="{% url 'web:index' %}">
      Amazon
    </a>

    <!-- Toggle button -->
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Welcome {{ request.session.name }}</a>
        </li>
      </ul>
      <!-- Left links -->

      <div class="d-flex align-items-center">
        <div>
          <a href="{% url 'web:myorder' %}">
            <button type="button" class="btn btn-primary px-3 me-2">My Orders
            </button>
          </a>
        </div>
        <div>
          <a href="{% url 'web:cart' %}">
            <button type="button" class="btn btn-primary px-3 me-2">Shopping cart
            </button>
          </a>
        </div>
        <div>
          <a href="{% url 'web:logout' %}">
            <button type="button" class="btn btn-secondary px-3 me-2">Logout
            </button>
          </a>
        </div>
      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>

docker-deploy/amazon/templates/web/rebindUpsAcc.html
<html>

<head>
  <meta charset="UTF-8">
  <title>Order Detail Page</title>
</head>


<body>
  <div id="includedContent"></div>
  <div class="container-xl px-4 mt-4">
    <div class="row">
      <div class="col-xl-8">
        <!-- Account details card-->
        <div class="card mb-4">
          <div class="card-header">Rebind your ups account!
          </div>
          <div class="card-body">
            <form action="{% url 'web:rebind_ups' slug=order.id %}" method="post">
              {% csrf_token %}
              <div class="row gx-3 mb-3">
                {{ rebind_form.upsAcc.label }}
                {{ rebind_form.upsAcc }}
              </div>
              <div>
                <a href="{% url 'web:myorder' %}" type="button" class="btn btn-primary" name='Back'>Back
                  to my orders
                </a>
                <button type="submit" class="btn btn-primary" name='rebind'>Rebind
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script>
  $(function () {
    $("#includedContent").load("../public");
  });
</script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">

docker-deploy/amazon/templates/web/register.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black" style="border-radius: 25px;">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                            <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>

                                <form method="post" class="mx-1 mx-md-4">
                                    {% csrf_token %}

                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                                        <div class="form-outline flex-fill mb-0">
                                            {{register_form.email.label}}
                                            {{register_form.email}}
                                        </div>
                                    </div>

                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                                        <div class="form-outline flex-fill mb-0">
                                            {{register_form.name.label}}
                                            {{register_form.name}}
                                        </div>
                                    </div>

                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                        <div class="form-outline flex-fill mb-0">
                                            {{register_form.password.label}}
                                            {{register_form.password}}
                                        </div>
                                    </div>

                                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4 btn-toolbar">
                                        <a href="{% url 'web:login' %}">
                                            <button type="button" class="btn btn-secondary btn-lg">Back to Login
                                            </button>
                                        </a>
                                        <button type="submit" class="btn btn-primary  ms-2">Register</button>
                                    </div>

                                </form>

                            </div>
                            <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                                    class="img-fluid" alt="Sample image">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</body>

</html>